### PR TITLE
Add missing stable Tier 2 platforms

### PR DESCRIPTION
**Pull request by bgermann**

### CODE REVIEW

**Comment by lilianmoraru** [comment]
Could you also please add `wasm32-unknown-unknown` or it will be added only after it reaches stable?

**Comment by bgermann** [comment]
I do not know what the exact policy is. There is one new stable target in version 23: x86_64-unknown-linux-gnux32

**Comment by bgermann** [comment]
I also see x86_64-linux-android is added in #59.

**Comment by bgermann** [comment]
Closing in favour of #132

**Pull request closed without merging**
