### PR TITLE
Update policy to handle prolonged inactive PRs.

### PR DESCRIPTION
**Pull request by Aaronepower**
This was proposed in the [last release team meeting](https://mozilla.logbot.info/rust-release).

### CODE REVIEW

**Comment by pietroalbini** [comment]
I'm not so sure about this, mostly due to GitHub limitations. PR authors can't reopen their PR if an org member closed them, but most importantly if they force push the whole PR is broken and it can't be reopened anymore.

The first problem can easily be fixed with a bot that reopens PRs labeled as inactive when the author interacts with them, but unfortunately we can't do anything about the second problem, and that's a common one (for example if there was a rebase).

**Comment by Aaronepower** [comment]
@pietroalbini I think the force push problem can be solved through letting the authors know that they shouldn't force push until the PR is reopened.  We could include a boilerplate message like. "**Warning** When you wish to come back to this PR **do not** force push or rebase your new code until the repository has been reopened."

**Comment by pietroalbini** [comment]
Well, yeah, that's not perfect but it could work. Still, I'd prefer if we automated posting the boilerplate, closing the PR, adding the label and reopening on activity before updating the policy.

**Comment by BatmanAoD** [comment]
@pietroalbini Doesn't force-pushing already have the capacity to corrupt PRs?

**Comment by BatmanAoD** [comment]
@pietroalbini Are we, though? I thought it didn't matter whether the PR is open or closed when the force push is made.

**Comment by shepmaster** [comment]
> force-pushing already have the capacity to corrupt open PRs?

What do you mean by "corrupt"?

**Comment by BatmanAoD** [comment]
@shepmaster I took the verbiage from a GitHub Help page: https://help.github.com/articles/about-pull-requests/

**Comment by pietroalbini** [comment]
@BatmanAoD I'm not talking about that, it's not documented AFAIK. If a PR is closed and you force push GitHub won't allow anybody to reopen it. And that's combined with the other problem that the author has to ping someone to reopen the PR in the first place.

**Comment by Aaronepower** [comment]
@Mark-Simulacrum Done.

**Pull request merged**
